name: echo-test-CI/CD
run-name: ğŸ”” @${{ github.actor }} was push up a new update at ${{ inputs.deploy_target }} ğŸ‘¾â¬†ï¸!
on:
  push:
    branches:
    - main
    - children-path
jobs:
  Github-Notification:
    runs-on: ubuntu-latest
    steps:
    - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - name: List files in the repository
      run: ls ${{ github.workspace }}
    - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
    - run: echo "ğŸ This job's status is ${{ job.status }}."
